global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: attendance-api
    static_configs:
      - targets: ["api:3000", "api-2:3000"]

  - job_name: attendance-worker
    static_configs:
      - targets: ["worker:9101"]
